platform :ios, '6.1'
pod 'AFNetworking'
#pod 'AFNetworking/UIKit+AFNetworking'
pod 'GoogleAnalytics-iOS-SDK'
pod 'Appirater'
pod 'FDTake'
pod 'MBProgressHUD'
pod 'NSData+Base64'
pod 'TDBadgedCell'
pod 'FDWaveformView'
