source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking'
#pod 'AFNetworking/UIKit+AFNetworking'
pod 'GoogleAnalytics-iOS-SDK'
pod 'Appirater'
pod 'FDTake'
pod 'MBProgressHUD'
pod 'NSData+Base64'
pod 'TDBadgedCell'
pod 'FDWaveformView'
