platform :ios, '6.1'
pod 'AFNetworking', '~> 0.10.1'
#pod 'AFNetworking/UIKit+AFNetworking'
pod 'GoogleAnalytics-iOS-SDK'
pod 'Appirater'
pod 'FDTake'
pod 'MBProgressHUD'
pod 'UIGlossyButton'
pod 'NSData+Base64'
